// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\laure\OneDrive\Documents\GitHub\int2\DevZone\Backend\app\user\user\repository.go

// Package mockUser is a generated GoMock package.
package mockUser

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	user "github.com/laureano/devzone/app/user/user"
	gorm "gorm.io/gorm"
)

// MockRepositoryDB_User is a mock of RepositoryDB_User interface.
type MockRepositoryDB_User struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryDB_UserMockRecorder
}

// MockRepositoryDB_UserMockRecorder is the mock recorder for MockRepositoryDB_User.
type MockRepositoryDB_UserMockRecorder struct {
	mock *MockRepositoryDB_User
}

// NewMockRepositoryDB_User creates a new mock instance.
func NewMockRepositoryDB_User(ctrl *gomock.Controller) *MockRepositoryDB_User {
	mock := &MockRepositoryDB_User{ctrl: ctrl}
	mock.recorder = &MockRepositoryDB_UserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryDB_User) EXPECT() *MockRepositoryDB_UserMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockRepositoryDB_User) GetUserByID(ctx context.Context, id uuid.UUID, tx *gorm.DB) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id, tx)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryDB_UserMockRecorder) GetUserByID(ctx, id, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryDB_User)(nil).GetUserByID), ctx, id, tx)
}

// RegisterUser mocks base method.
func (m *MockRepositoryDB_User) RegisterUser(ctx context.Context, user user.User, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, user, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockRepositoryDB_UserMockRecorder) RegisterUser(ctx, user, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockRepositoryDB_User)(nil).RegisterUser), ctx, user, tx)
}
