// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\laure\OneDrive\Documents\GitHub\int2\DevZone\Backend\app\categories_tag\category\repository.go

// Package mockCategory is a generated GoMock package.
package mockCategory

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	category "github.com/laureano/devzone/app/categories_tag/category"
	gorm "gorm.io/gorm"
)

// MockRepositoryDB_Category is a mock of RepositoryDB_Category interface.
type MockRepositoryDB_Category struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryDB_CategoryMockRecorder
}

// MockRepositoryDB_CategoryMockRecorder is the mock recorder for MockRepositoryDB_Category.
type MockRepositoryDB_CategoryMockRecorder struct {
	mock *MockRepositoryDB_Category
}

// NewMockRepositoryDB_Category creates a new mock instance.
func NewMockRepositoryDB_Category(ctrl *gomock.Controller) *MockRepositoryDB_Category {
	mock := &MockRepositoryDB_Category{ctrl: ctrl}
	mock.recorder = &MockRepositoryDB_CategoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryDB_Category) EXPECT() *MockRepositoryDB_CategoryMockRecorder {
	return m.recorder
}

// ListCategories mocks base method.
func (m *MockRepositoryDB_Category) ListCategories(ctx context.Context, tx *gorm.DB) ([]category.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, tx)
	ret0, _ := ret[0].([]category.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockRepositoryDB_CategoryMockRecorder) ListCategories(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockRepositoryDB_Category)(nil).ListCategories), ctx, tx)
}
