// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\laure\OneDrive\Documents\GitHub\int2\DevZone\Backend\identity\identities.go

// Package mockKeycloak is a generated GoMock package.
package mockKeycloak

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	identity "github.com/laureano/devzone/identity"
)

// MockRepositoryIdentities is a mock of RepositoryIdentities interface.
type MockRepositoryIdentities struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryIdentitiesMockRecorder
}

// MockRepositoryIdentitiesMockRecorder is the mock recorder for MockRepositoryIdentities.
type MockRepositoryIdentitiesMockRecorder struct {
	mock *MockRepositoryIdentities
}

// NewMockRepositoryIdentities creates a new mock instance.
func NewMockRepositoryIdentities(ctrl *gomock.Controller) *MockRepositoryIdentities {
	mock := &MockRepositoryIdentities{ctrl: ctrl}
	mock.recorder = &MockRepositoryIdentitiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryIdentities) EXPECT() *MockRepositoryIdentitiesMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockRepositoryIdentities) GetUserByID(ctx context.Context, id string) (*identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryIdentitiesMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryIdentities)(nil).GetUserByID), ctx, id)
}
