// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\laure\OneDrive\Documents\GitHub\int2\DevZone\Backend\app\post\post\repository.go

// Package mockPost is a generated GoMock package.
package mockPost

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	post "github.com/laureano/devzone/app/post/post"
	gorm "gorm.io/gorm"
)

// MockRepositoryDB_Post is a mock of RepositoryDB_Post interface.
type MockRepositoryDB_Post struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryDB_PostMockRecorder
}

// MockRepositoryDB_PostMockRecorder is the mock recorder for MockRepositoryDB_Post.
type MockRepositoryDB_PostMockRecorder struct {
	mock *MockRepositoryDB_Post
}

// NewMockRepositoryDB_Post creates a new mock instance.
func NewMockRepositoryDB_Post(ctrl *gomock.Controller) *MockRepositoryDB_Post {
	mock := &MockRepositoryDB_Post{ctrl: ctrl}
	mock.recorder = &MockRepositoryDB_PostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryDB_Post) EXPECT() *MockRepositoryDB_PostMockRecorder {
	return m.recorder
}

// AddCategorieInPost mocks base method.
func (m *MockRepositoryDB_Post) AddCategorieInPost(ctx context.Context, tx *gorm.DB, post *post.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategorieInPost", ctx, tx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCategorieInPost indicates an expected call of AddCategorieInPost.
func (mr *MockRepositoryDB_PostMockRecorder) AddCategorieInPost(ctx, tx, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategorieInPost", reflect.TypeOf((*MockRepositoryDB_Post)(nil).AddCategorieInPost), ctx, tx, post)
}

// CreatePost mocks base method.
func (m *MockRepositoryDB_Post) CreatePost(ctx context.Context, tx *gorm.DB, post *post.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, tx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockRepositoryDB_PostMockRecorder) CreatePost(ctx, tx, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockRepositoryDB_Post)(nil).CreatePost), ctx, tx, post)
}

// ListPosts mocks base method.
func (m *MockRepositoryDB_Post) ListPosts(ctx context.Context, tx *gorm.DB) ([]post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx, tx)
	ret0, _ := ret[0].([]post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockRepositoryDB_PostMockRecorder) ListPosts(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockRepositoryDB_Post)(nil).ListPosts), ctx, tx)
}
